- .github/CODEOWNERS
> chore: add team members as codeowners [skip ci]

- packages/integration-react/README.md
- packages/integration-react/package.json
exposes cjs for react native
fixes #10
> feat(react): expose cjs for react native

- .github/PULL_REQUEST_TEMPLATE.md
fixes a typo in the pull request template
> ci: fix typo in pull request template

- .commitlintrc
- .gitignore
- examples/react18/README.md
- examples/react18/package.json
- examples/react18/public/index.html
- examples/react18/src/App.tsx
- examples/react18/src/TestComponent.tsx
- examples/react18/src/index.tsx
- examples/react18/tsconfig.json
- package.json
- yarn.lock
> feat(examples): add react 18 example app

- examples/node/package.json
- examples/node/src/index.js
- examples/nodeCJS/package.json
- examples/nodeCJS/src/index.js
- packages/openfeature-server-provider/README.md
- yarn.lock
Adding a node example and updating the server provider docs to be more accurate.
> Server docs update

- examples/react18/package.json
- packages/integration-react/package.json
- packages/integration-react/src/ReactAdapter.test.tsx
- packages/integration-react/src/ReactAdaptor.tsx
- yarn.lock
Currently we only trigger a re-render of the page on the first context change. This PR fixes that and allows for multiple context changes to happen, also simplifies the react implementation logic.
> React improvements

- examples/next12/utils/setupOpenFeatureConfidenceProvider.ts
- examples/next13/utils/clientProvider.ts
- examples/next13/utils/setupOpenFeatureConfidenceProvider.ts
- examples/node/src/index.js
- examples/nodeCJS/src/index.js
- examples/react18/src/App.tsx
- packages/client-http/src/client/ConfidenceClient.test.ts
- packages/client-http/src/client/ConfidenceClient.ts
- packages/integration-react/src/ReactAdapter.e2e.test.tsx
- packages/openfeature-server-provider/README.md
- packages/openfeature-server-provider/src/ConfidenceServerProvider.e2e.test.ts
- packages/openfeature-server-provider/src/factory.ts
- packages/openfeature-web-provider/README.md
- packages/openfeature-web-provider/src/ConfidenceWebProvider.e2e.test.ts
- packages/openfeature-web-provider/src/factory.ts
Add a timeout for the network request
> Add timeout

- README.md
> docs: add Confidence link to the README

- packages/integration-react/README.md
Timeout is missing from the docs for integration react, this PR adds it in
> docs(react): add timeout to docs

- .github/CODEOWNERS
> ci: update code oweners

- packages/client-http/src/client/Configuration.ts
- packages/openfeature-server-provider/src/ConfidenceServerProvider.test.ts
- packages/openfeature-web-provider/src/ConfidenceWebProvider.test.ts
> fix: allow the full flag to be resolved

- .github/actions/setup/action.yml
- .github/workflows/Build.yml
- .github/workflows/Release-Please.yml
- yarn.lock
> ci: release please does not run on frozen lockfile

- examples/react18/src/TestComponent.tsx
- packages/sdk/src/Confidence.e2e.test.ts
> docs: update sendEvent in example app

- packages/integration-react/README.md
- packages/openfeature-server-provider/README.md
- packages/openfeature-web-provider/README.md
Slight changes to Readme docs combined with `Release-As` to nudge Release please to set correct versions.
> chore: remove rc from versions

- README.md
- packages/sdk/README.md
> docs: update main README.md

- .github/workflows/Release-Please.yml
- packages/openfeature-server-provider/package.json
- packages/openfeature-web-provider/package.json
- packages/sdk/package.json
- yarn.config.cjs
> build: simplify npm deployment

- packages/sdk/src/trackers/pageViews.ts
> fix: pageviews: handle missed load event

- .github/actions/setup/action.yml
- .github/workflows/Release-Please.yml
> ci: run RP with setup-node@v3

- .github/workflows/Release-Please.yml
using yarn config set instead of manually appending to .yarnrc.yaml
> fix: fix npm publishing

- packages/openfeature-server-provider/package.json
- packages/openfeature-web-provider/package.json
- packages/react/package.json
- yarn.lock
This fix unbreaks the `main` branch but we believe that this situation will occur again due to how release please works.
> fix: build issues

- .github/workflows/Amend-Release.yml
- .github/workflows/Build.yml
This is another attempt at having the release please branch be built automatically. But should also support running the job "manually".
> ci: attempt to run CI build after release amends using workflow dispatch

- examples/nodeCJS/src/index.js
- package.json
- packages/openfeature-server-provider/package.json
- packages/openfeature-web-provider/package.json
- packages/react/package.json
- packages/sdk/package.json
- rollup.base.mjs
- yarn.config.cjs
- yarn.lock
With this PR we're additionally building out a "common-js" module to natively support legacy CommonJS projects.
> feat: add support for common-js module

- packages/sdk/README.md
Note to highlight the importance of using `withContext` in server environments.
> docs: clarify importance of withContext in server usage

- packages/sdk/README.md
Fix correct styling of "alert box"
> docs: fix styling of alert box

- examples/node/src/index.js
- examples/nodeCJS/package.json
- examples/nodeCJS/src/index.js
* Removed duplicate constant name in node cjs example app
* Add use of environment file in `yarn dev`
* fix spelling
> fix: fix issue in commonjs example app

- api/sdk.api.md
- packages/sdk/src/Confidence.ts
- packages/sdk/src/FlagResolverClient.test.ts
- packages/sdk/src/FlagResolverClient.ts
- packages/sdk/src/index.ts
- packages/sdk/src/types.ts
> feat: waitUntil option to register async side-effects

- packages/sdk/src/Confidence.ts
- packages/sdk/src/FlagResolverClient.test.ts
- packages/sdk/src/FlagResolverClient.ts
- packages/sdk/src/fetch-util.ts
This PR addresses some of the concerns brought up by [this issue](https://github.com/spotify/confidence-sdk-js/issues/221) and adds better logging for missing or invalid client key.
> refactor: add better logging for invalid or missing client key

- packages/openfeature-server-provider/package.json
- packages/openfeature-web-provider/package.json
- packages/react/package.json
- yarn.lock
The versions will be compatible up until 0.4.0.
> fix: set correct peer deps

- packages/openfeature-web-provider/src/ConfidenceWebProvider.e2e.test.ts
- packages/sdk/src/Confidence.e2e.test.ts
- packages/sdk/src/Confidence.test.ts
- packages/sdk/src/Value.test.ts
- packages/sdk/src/Value.ts
Null values in context were causing crashes
> fix: null Value treated as undefined, fix crashes

- packages/sdk/README.md
> docs: add docs about logging

- README.md
- packages/openfeature-server-provider/README.md
- packages/openfeature-web-provider/README.md
- packages/react/README.md
- packages/sdk/README.md
- Changed the README in the root folder to give a better overview of the different packages and provide a quick overview of how to use the SDK with OpenFeature in both a client- and a server-side environment. 
- Added docs of how to use the sdk in an SSR environment and link to example application 
- Fixed minor errors
> docs: restructure and update to docs
