spotify/confidence-sdk-js

- packages/client-http/tsconfig.cjs.json
- packages/client-http/tsconfig.esm.json
- packages/integration-react/tsconfig.cjs.json
- packages/integration-react/tsconfig.esm.json
- packages/openfeature-server-provider/tsconfig.cjs.json
- packages/openfeature-server-provider/tsconfig.esm.json
- packages/openfeature-web-provider/tsconfig.cjs.json
- packages/openfeature-web-provider/tsconfig.esm.json
Builds were not correctly using the common js format
> fix: ensure the target output is esm or cjs

- .github/CODEOWNERS
Adding team members to the list of code owners to approve PRs
> chore: add team members as codeowners [skip ci]

- packages/openfeature-server-provider/package.json
- packages/openfeature-server-provider/src/ConfidenceServerProvider.test.ts
- packages/openfeature-server-provider/src/ConfidenceServerProvider.ts
Previously we were caching the server request of a flag on the context, this can result in issues when handling multiple concurrent requests, also it can mean we never update to reflect changes made in the confidence console
> fix(server): do not cache request

- .gitignore
- examples/next12/README.md
- examples/next12/package.json
- examples/next12/pages/api/next12.ts
- examples/next12/pages/next12/index.tsx
- examples/next12/tsconfig.json
- examples/next12/utils/setupOpenFeatureConfidenceProvider.ts
- examples/next13/README.md
- examples/next13/app/layout.tsx
- examples/next13/app/next13Advanced/ClientComponent.tsx
- examples/next13/app/next13Advanced/page.tsx
- examples/next13/app/next13Advanced/setOpenFeatureContext.tsx
- examples/next13/app/next13Simple/SimpleClientComponent.tsx
- examples/next13/app/next13Simple/api/route.ts
- examples/next13/app/next13Simple/page.tsx
- examples/next13/package.json
- examples/next13/pages/api/next12Simulation.ts
- examples/next13/pages/next12Simulation/index.tsx
- examples/next13/tsconfig.json
- examples/next13/utils/ClientBoundary.tsx
- examples/next13/utils/clientProvider.ts
- examples/next13/utils/setupOpenFeatureConfidenceProvider.ts
- packages/integration-react/README.md
- packages/integration-react/src/ReactAdaptor.tsx
- yarn.lock
Add documentation and example apps for usage in Next 12 and Next 13.
Add `use client` directive to the React Adapter to tell Next13 to include in the client bundle and warn about server side use.
> Nextjs improvements

- packages/client-http/src/client/ConfidenceClient.test.ts
- packages/client-http/src/client/ConfidenceClient.ts
- packages/openfeature-server-provider/src/factory.ts
- packages/openfeature-web-provider/src/factory.ts
- release-please-config.json
- yarn.lock
We can now send the sdk version in the resolve request. This PR enables this for the web and server providers
> Send SDK version 

- packages/client-http/src/ApplyManager.test.ts
- packages/client-http/src/ApplyManager.ts
- packages/openfeature-web-provider/src/ConfidenceWebProvider.ts
closes #36 by setting a max size of the apply buffer, only applicable in web.
Need to update the docs when the apply documentation PR is merged. (#33 )
> Max buffer size

- packages/integration-react/README.md
An issue was pointed out that in the web provider docs we talk about not setting the provider before the context because of the issues with resolving with no context triggering a Provider ready event, meaning the UI might show with the default values before flashing to the actual values once the setContext call has completed. The PR updates to docs to make sure that issue is surfaced for people only viewing the react documentation.
> docs(react): add note on setting provider before setting context

- examples/node/src/index.js
- packages/client-http/src/client/ConfidenceClient.test.ts
- packages/client-http/src/client/ConfidenceClient.ts
- packages/integration-react/README.md
- packages/integration-react/src/ReactAdapter.e2e.test.tsx
- packages/openfeature-server-provider/README.md
- packages/openfeature-server-provider/src/ConfidenceServerProvider.e2e.test.ts
- packages/openfeature-server-provider/src/factory.ts
- packages/openfeature-web-provider/README.md
- packages/openfeature-web-provider/src/ConfidenceWebProvider.e2e.test.ts
- packages/openfeature-web-provider/src/factory.ts
This PR allows you to opt of selecting a region for your resolver, to use the default (global) region. You can also manually input 'global' to be explicit. The default is now to use the global resolver.
> Add global url

- packages/client-http/src/ApplyManager.test.ts
- packages/client-http/src/ApplyManager.ts
Before apply events could be duplicated if the ApplyManager was flushed (which happens on buffer overflow) while a apply request was already in progress. This is fixed by clearing pendingApply while a request is in progress and adding them back if the request fails. Also refactored the code a bit to make it easier to follow.
The apply logic still has some shortcomings, but these will be adressed in a followup PR.
> fix: Duplicate apply bug

- packages/client-http/src/client/ConfidenceClient.test.ts
- packages/client-http/src/client/ConfidenceClient.ts
- packages/openfeature-server-provider/package.json
- packages/openfeature-web-provider/package.json
- yarn.lock
Start sending SDK information with apply events. The PR also pins the shared `@spotify-confidence/client-http` dependency to an exakt version so we can now the setup from just the provider version.
> feat: send sdk info with apply events

- customJestBrowserEnv.ts
- jest.config.js
- packages/client-http/package.json
- packages/integration-react/package.json
- packages/integration-react/src/ReactAdapter.e2e.test.tsx
- packages/openfeature-server-provider/src/ConfidenceServerProvider.e2e.test.ts
- packages/openfeature-server-provider/src/factory.ts
- packages/openfeature-web-provider/src/ConfidenceWebProvider.e2e.test.ts
- packages/openfeature-web-provider/src/factory.ts
- yarn.lock
This PR updates all tests to use the global fetch implementation, both in browsers and NodeJS. Before we were using a mix of different hacked fetch implementations.
It also makes the `fetchImplementation` setting optional when creating a provider, and defaults this setting to use the global fetch, and throwing an error if it doesn't exist.
> Use a default fetch implementation

- packages/client-http/src/fetch-util.test.ts
- packages/client-http/src/fetch-util.ts
- packages/client-http/src/index.ts
- packages/openfeature-web-provider/src/factory.test.ts
- packages/openfeature-web-provider/src/factory.ts
- packages/openfeature-web-provider/src/index.ts
_Note: This is still work in progress, if we're happy with the overall logic, more tests are needed_
This PR hardens the logic for making requests to our backend. This is achieved through a new class `FetchBuilder` which allows to augment the fetch client with some request logic primitives like `retry`, `rate-limit` and `timeout` etc.  These primitives are used to build two separate fetch clients for resolve and apply with the following goals:
- Whenever there is a new request, abort the previous one since there is no point in applying those stale values.
- Add a timeout to each call. This is the only user-configurable option and dictates how long the user is prepared to wait before giving up and falling back on default values.
- Retry unlimited number of times until the timeout
- Rate …
> feat(client-http): improved retry logic

- packages/client-http/src/fetch-util.test.ts
- packages/client-http/src/fetch-util.ts
This fixes an edge case that if a request was already aborted when entering retry, the abort itself would trigger more retries.
> fix(client-http): do not retry aborted requests

- .github/workflows/Release-Please.yml
- yarn.lock
As a temporary workaround for limitations in Release-Please, we will allow `yarn build` in the publish step to modify the lock-file.
> ci: allow lockfile changes in publish build

- .github/workflows/Amend-Release.yml
The idea with this workflow is to run on top of every release-please PR and amend it by running `yarn build`, generating potential changes to the `yarn.lock` file. 
Right now I don't know if this will actually be triggered since the Release-please workflow is run by a bot and any actions done by it will not trigger other (this) workflows. (As per [this](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow))
> If you do want to trigger a workflow from within a workflow run, you can use a GitHub App installation access token or a personal access token instead of GITHUB_TOKEN to trigger events that require a token.
> ci: amend releases

- packages/openfeature-web-provider/src/ConfidenceWebProvider.test.ts
- packages/openfeature-web-provider/src/ConfidenceWebProvider.ts
> fix: return the prev assigned value while provider is stale

- packages/sdk/src/Confidence.e2e.test.ts
- packages/sdk/src/EventSenderEngine.test.ts
- packages/sdk/src/EventSenderEngine.ts
Created new flag `js-sdk-e2e-tests` in the backend, due to some irreversible schema changes mistakenly added to `js-sdk-e2e-test`
> refactor: add message container to payload

- packages/openfeature-web-provider/src/ConfidenceWebProvider.ts
- packages/sdk/src/Confidence.e2e.test.ts
- packages/sdk/src/Confidence.ts
- packages/sdk/src/EventSenderEngine.ts
- packages/sdk/src/logger.ts
- packages/sdk/src/trackers/pageViews.ts
Use the console as a default alternative for development mode apps. Will log at info level.
> feat: default info logging to console in development

- api/sdk.api.md
- packages/openfeature-server-provider/src/ConfidenceServerProvider.ts
- packages/openfeature-web-provider/src/ConfidenceWebProvider.ts
- packages/sdk/src/Confidence.ts
- packages/sdk/src/Value.ts
- packages/sdk/src/flags.ts
Right now we have an issue that flag value types are too aggressively "narrowed" by TS. For instance:
```
const value = await confidence.getFlag('ff', 3);
```
Right now TS will infer the type of value to be `3` withe the desired type being `number`. This PR fixes that. Ideally we should have type tests for this sort of thing. But that is saved for another day.
> fix: widen flag return types

- packages/sdk/src/AccessiblePromise.test.ts
- packages/sdk/src/AccessiblePromise.ts
- packages/sdk/src/FlagResolverClient.ts
Fixes a bug in PendingResolution that caused an avalanche of AccessiblePromises being created for each then, catch of finally call.
> fix: excessive promises created by PendingResolution

- api/react.api.md
- api/sdk.api.md
- examples/react18/src/App.tsx
- examples/react18/src/index.tsx
- packages/openfeature-server-provider/src/ConfidenceServerProvider.ts
- packages/openfeature-web-provider/src/ConfidenceWebProvider.e2e.test.ts
- packages/openfeature-web-provider/src/ConfidenceWebProvider.test.ts
- packages/openfeature-web-provider/src/ConfidenceWebProvider.ts
- packages/react/src/index.tsx
- packages/sdk/src/Confidence.test.ts
- packages/sdk/src/Confidence.ts
- packages/sdk/src/FlagResolution.ts
- packages/sdk/src/FlagResolverClient.test.ts
- packages/sdk/src/FlagResolverClient.ts
- packages/sdk/src/flags.ts
- packages/sdk/src/observing.ts
Move resolve timeout functionality to the FlagResolverClient, which in turn fixes two problems:
1. Failing requests aren't any longer retried indefinitely.
2. Failed requests are now cached so that they also work with Reac Suspense.
Fixes #155
> fix: cache timeouts

- packages/sdk/src/logger.ts
Without the exported `LEVELS`, typescript is forced to generate an empty export statement, this in turn triggers a bug in the `api-extractor` bundle tool.
> fix: invalid d.ts generation

- api/react.api.md
- examples/react18/src/App.tsx
- packages/react/README.md
- packages/react/src/index.tsx
- Stop subscribing in useConfidence
- Subscribe to contextChanges in all hooks that depend on context (useFlagXXX, useContext)
- Handle stale flags through React transitions
> feat: improved suspense management

- packages/sdk/src/FlagResolverClient.test.ts
- packages/sdk/src/FlagResolverClient.ts
Due to the client cache resolve requests can be shared. We keep a ref-count in the cache entries and clear the entry when the ref-count drops to zero. However we inadvertently aborted the original request as soon as any ref was aborted. Added tests to show this and a fix.
> fix: shared requests aborted

- packages/sdk/src/Confidence.ts
This PR will make the `CachingFlagResolverClient` persist the cache in memory for an infinite time.
> fix: infinite in memory flag cache

- yarn.config.cjs
We already enforce that every peer dependency has a dev dependency with 
```ts
dep.workspace.set(['devDependencies', dep.ident], dep.range.slice(1));
```
This will not block us from defining different dev dependencies between the packages in the workspace.
> chore: allow for mixed dev-deps in the workspace

- packages/openfeature-server-provider/package.json
- packages/openfeature-web-provider/package.json
- yarn.lock
This PR reverts the dependency upgrading as the issue of having to upgrade all dependencies across the workplace has been fixed.
> chore!: revert dependencies

- api/openfeature-server-provider.api.md
- api/openfeature-web-provider.api.md
- api/react.api.md
- api/sdk.api.md
- packages/openfeature-server-provider/src/ConfidenceServerProvider.ts
- packages/openfeature-server-provider/src/factory.ts
- packages/openfeature-web-provider/src/ConfidenceWebProvider.ts
- packages/openfeature-web-provider/src/factory.ts
- packages/react/src/index.tsx
- packages/sdk/src/Closer.ts
- packages/sdk/src/Confidence.ts
- packages/sdk/src/Trackable.ts
- packages/sdk/src/Value.ts
- packages/sdk/src/context.ts
- packages/sdk/src/events.ts
- packages/sdk/src/flags.ts
- packages/sdk/src/trackers/pageViews.ts
- packages/sdk/src/trackers/visitorId.ts
- packages/sdk/src/trackers/webVitals.ts
- packages/sdk/src/utils.ts
This PR is adding documentation placeholders that resolve most of the issues in the generated API reports.
> Docs: Add documentation to the SDK to resolve MD warnings

- api/sdk.api.md
- packages/sdk/src/Confidence.ts
We don't want our users to use the Confidence constructor but rather the `create()` method.
Note: This should be considered a breaking change.
> fix!: mark Confidence constructor as internal

- api/react.api.md
- api/sdk.api.md
- packages/react/src/index.tsx
- packages/sdk/src/Confidence.ts
- packages/sdk/src/Value.ts
- packages/sdk/src/flags.ts
This PR removes the "Widen<T>" type which was there as a fix for return types being referred too narrowly. For instance the return value of `getFlag` should be of the same type as the default value arg. But if you called getFlag with a `3` as the default value the inferred return type would be `3` instead of `number`. The Widen type caused some unnecessary complexity though, and now the problem is fixed with overloads instead.
> refactor: remove the widen type

- packages/sdk/README.md
- packages/sdk/src/Confidence.ts
We want to allow users to opt out from `visitor_id` which is a feature that uses cookies as a storage medium.
Since we are defaulting to disable visitor id (whereas it was previously enabled), we mark the commit as breaking.
> fix!: visitor id disabled by default

- api/sdk.api.md
- packages/sdk/src/Confidence.int.test.ts
- packages/sdk/src/Confidence.ts
- packages/sdk/src/FlagResolverClient.ts
With this PR, we're adding a possibility to use a custom url in order to sidecar resolves.
> feat: add a custom baseURL for sidecar resolves

- api/sdk.api.md
- packages/sdk/src/Confidence.test.ts
- packages/sdk/src/Confidence.ts
This PR adds a link to logger which can be used to access resolve debug tool in console.
> feat: Resolve Debug to redirect to UI tool on web

- README.md
- examples/node/package.json
- examples/node/src/index.js
- packages/sdk/README.md
- yarn.lock
This PR should update the Readme to make it clearer how to setup vanilla Confidence SDK.
> docs: Revamp readme

- api/sdk.api.md
- packages/sdk/src/Confidence.ts
- packages/sdk/src/FlagResolverClient.test.ts
- packages/sdk/src/FlagResolverClient.ts
Making apply debounce (previously named timeout) configurable from the outside (when creating Confidence instance).
Also making sure that setting the applyDebounce to 0 the apply function is called synchronously (or without `setTimeout`).
> feat: configurable apply debounce

- README.md
- packages/sdk/README.md
- packages/sdk/src/Confidence.ts
Fix the documentation so that it does not trick people and validate the string passed to the environment.
> fix: create a safe environment

- packages/sdk/src/Confidence.ts
- packages/sdk/src/Telemetry.test.ts
- packages/sdk/src/Telemetry.ts
I grew tired of the telemetry outputs and made it optional and stopped passing it.
> fix: make telemetry Logger optional (and don't pass it)

- .eslintrc
- api/sdk.api.md
- packages/sdk/src/Confidence.ts
- packages/sdk/src/EventSenderEngine.ts
- packages/sdk/src/FlagResolverClient.test.ts
- packages/sdk/src/FlagResolverClient.ts
- packages/sdk/src/fetch-util.test.ts
- packages/sdk/src/fetch-util.ts
- packages/sdk/src/index.ts
- packages/sdk/src/types.ts
Minimal fix to circumvent the [this](https://github.com/nodejs/undici/issues/4068) bug in node which looses AbortSignals on cloned requests which in turn makes our retries infinite. The idea of the fix is to avoid creating requests in FetchBuilder until the very last step just before sending the request.
fixes #221
> fix: avoid cloning requests in FetchBuilder

- packages/openfeature-server-provider/package.json
- packages/openfeature-web-provider/package.json
- packages/react/package.json
- packages/sdk/package.json
- yarn.config.cjs
The `pack` for the react package did not include the `/client/*` and `/server/*`. We decided to just go with the full contents of the dist.
> fix: include correct dist files

- api/react-server.d.ts
- api/react.d.ts
- package.json
- packages/react/README.md
- packages/react/package.json
- packages/react/rollup.config.mjs
- packages/react/src/index.tsx
- packages/react/src/server.tsx
- yarn.config.cjs
- yarn.lock
BREAKING CHANGE:
Previously, when you did `useConfidence`, the returned instance would be augmented with extra hook-like functions such as `useFlag`. These have been removed and you should just use the exported top level hooks.
---------
> feat(react): react server support

- packages/openfeature-web-provider/README.md
Update to docs to show that setProviderAndWait can throw. Following the OF PR: https://github.com/open-feature/js-sdk/pull/1180
> docs: clarify in example that setProviderAndWait may throw

- packages/sdk/src/Confidence.ts
- packages/sdk/src/utils.ts
Resolver hint logs will now contain a base64 encoded string which can be pasted in the Confidence tools to support that we don't necessarily know the URL the user would want to use.
> fix: update the resolver tester message to exclude link

- api/openfeature-server-provider.d.ts
- packages/openfeature-server-provider/src/factory.ts
This will allow you to pass the `resolveBaseUrl` directly when using `createConfidenceServerProvider()`
> fix: add support for resolveUrl in createConfidenceServerProvider()

- packages/sdk/src/FlagResolverClient.ts
When running Confidence on constrained resources we could see that a evaluateFlag call could hang indefinitely if the timeout triggered (abortsignal fired) between the time that the response headers came back and the time Node was finished consuming the fetch stream and transforming it to json.
We now manually make sure that the timeout signal is respected.
> fix: defensively reject if aborted during response.json()
